#!/bin/bash
# 24h GitHub 学习管道 - 小服务器 → 回传大机(明月)
# 定时: 拉 GitHub 热榜 + AI 新工具情报 → 生成知识笔记 → 回传大机
# 回传目标由 env TARGET_HOST / TARGET_USER / TARGET_DIR 控制
WORK=/srv/gh-learn
mkdir -p "$WORK/notes"
cd "$WORK"
STAMP=$(date +%Y%m%d-%H%M)
OUT="$WORK/notes/learn-$STAMP.md"

PY="python3"
JQ_ITEM='import sys,json
d=json.load(sys.stdin)
for i in d.get("items",[])[:10]:
    print("- [%s] star%s | %s" % (i["full_name"], i.get("stargazers_count"), (i.get("description") or "")[:100]))'

{
echo "# 📚 GitHub 知识学习 $STAMP"
echo ""
echo "## 🔥 今日 Trending(最热仓库)"
curl -s --max-time 20 "https://api.github.com/search/repositories?q=stars:%3E500&sort=stars&order=desc&per_page=10" \
  | $PY -c "$JQ_ITEM" 2>/dev/null || echo "(trending 抓取失败)"

echo ""
echo "## 🔧 新工具/技能关键词扫描"
for KW in "ai-tool" "claude-skill" "local-llm" "agent-framework" "automation"; do
  echo "- **$KW**:"
  curl -s --max-time 15 "https://api.github.com/search/repositories?q=$KW&sort=updated&order=desc&per_page=3" \
    | $PY -c "$JQ_ITEM" 2>/dev/null || echo "  (无)"
done

echo ""
echo "## 📈 关键 AI 开源大仓库动态"
for R in "huggingface/transformers" "ollama/ollama" "openai/openai-python" "microsoft/autogen" "Aider-AI/aider" "langchain-ai/langchain"; do
  INFO=$(curl -s --max-time 10 "https://api.github.com/repos/$R" \
    | $PY -c 'import sys,json
d=json.load(sys.stdin)
print("%sstar | Pushed %s | %s" % (d.get("stargazers_count",0), d.get("pushed_at","?"), (d.get("description") or "")[:70]))' 2>/dev/null)
  echo "- **$R** — $INFO"
done

echo ""
echo "_Generated by 24h GitHub learn pipeline_"
} > "$OUT"

echo "✅ 笔记已生成: $OUT ($(wc -l < "$OUT") 行)"

# ---- 回传大机(明月) ----
TARGET_HOST="${TARGET_HOST:-121.40.246.94}"
TARGET_USER="${TARGET_USER:-root}"
TARGET_DIR="${TARGET_DIR:-/root/.openclaw/workspace/reference/miniserver-learn}"
if command -v scp >/dev/null 2>&1; then
  mkdir -p "$WORK/sent"
  # 尝试免密回传(scp 用 22, 显式指定回传私钥)
  if scp -i /root/.ssh/ghlearn_ed25519 -o BatchMode=yes -o ConnectTimeout=10 -o StrictHostKeyChecking=no "$OUT" "$TARGET_USER@$TARGET_HOST:$TARGET_DIR/$(basename "$OUT")" 2>/dev/null; then
    echo "✅ 已回传大机: $TARGET_HOST:$TARGET_DIR"
    mv "$OUT" "$WORK/sent/"
  else
    echo "⚠️ 免密回传失败(需在大机配 authorized_keys), 笔记保留在 $OUT"
  fi
else
  echo "⚠️ 无 scp, 笔记保留在 $OUT"
fi
